"""BFYP VAULT V2 — 30-Reel slate: concepts, scripts, captions, sources.

Single source of truth used to generate every per-reel deliverable sheet.
All BFYP screens were captured 23 Sep 2026 (UTC) and are stamped on screen.
"""

CAPTURE_NOTE = "Real BFYP screens captured 23 Sep 2026 (UTC). Live data changes."
DISCLAIMER = "Educational market data. Not financial advice."
SITE = "betterforyourpocket.com"

SRC = {
    "sec_x": {"name": "SEC — SECGov X Account (unauthorized post, 9 Jan 2024)", "url": "https://www.sec.gov/secgov-x-account", "date": "Jan 2024"},
    "gensler_x": {"name": "Gary Gensler post, 9 Jan 2024, 4:26 pm ET", "url": "https://x.com/GenslerArchive/status/1744833049064288387", "date": "9 Jan 2024"},
    "sec_approval": {"name": "SEC — Gensler statement on spot bitcoin ETP approval", "url": "https://www.sec.gov/newsroom/speeches-statements/gensler-statement-spot-bitcoin-011023", "date": "10 Jan 2024"},
    "doj_sec_hack": {"name": "U.S. DOJ — sentencing in SEC X account hack (BTC moves: +$1,000 / -$2,000 per BTC)", "url": "https://www.justice.gov/opa/pr/alabama-man-sentenced-14-months-connection-securities-and-exchange-commission-x-hack-spiked", "date": "16 May 2025"},
    "sec_2022_221": {"name": "SEC press release 2022-221", "url": "https://www.sec.gov/newsroom/press-releases/2022-221", "date": "14 Dec 2022"},
    "ca5_2025": {"name": "U.S. Court of Appeals, 5th Cir., No. 24-20143 (indictment reinstated)", "url": "https://www.ca5.uscourts.gov/opinions/pub/24/24-20143-CV0.pdf", "date": "2 Oct 2025"},
    "form4": {"name": "SEC Form 4 — General Instructions (filing deadline)", "url": "https://www.sec.gov/files/form4.pdf", "date": "current"},
    "mata": {"name": "Mata v. Avianca, No. 22-cv-1461 (PKC) (S.D.N.Y.), sanctions opinion", "url": "https://www.courtlistener.com/opinion/9885417/mata-v-avianca-inc/", "date": "22 Jun 2023"},
    "ap_cnbc": {"name": "CNBC — False rumor of explosion at White House causes stocks to briefly plunge (Reuters data: $136.5B)", "url": "https://www.cnbc.com/2013/04/23/false-rumor-of-explosion-at-white-house-causes-stocks-to-briefly-plunge-ap-confirms-its-twitter-feed-was-hacked.html", "date": "23 Apr 2013"},
    "ap_reuters_abc": {"name": "Reuters report via ABC News (AU) — AP Twitter feed hacked", "url": "https://www.abc.net.au/news/2013-04-24/ap-twitter-feed-hacked/4647630", "date": "24 Apr 2013"},
    "ftc_reviews": {"name": "FTC press release — Final Rule Banning Fake Reviews and Testimonials", "url": "https://www.ftc.gov/news-events/news/press-releases/2024/08/federal-trade-commission-announces-final-rule-banning-fake-reviews-testimonials", "date": "14 Aug 2024"},
    "finra_genz": {"name": "FINRA Foundation & CFA Institute — Gen Z and Investing (press release)", "url": "https://www.finra.org/media-center/newsreleases/2023/finra-foundation-cfa-institute-research-focuses-gen-z-investors", "date": "24 May 2023"},
    "form13f": {"name": "Investor.gov — Form 13F (filed within 45 days of quarter end)", "url": "https://www.investor.gov/introduction-investing/investing-basics/glossary/form-13f-reports-filed-institutional-investment", "date": "current"},
    "nvda_fy26": {"name": "NVIDIA — Financial results for Q4 and fiscal 2026 (fiscal year ended 25 Jan 2026)", "url": "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-fourth-quarter-and-fiscal-2026", "date": "25 Feb 2026"},
    "nvda_10k": {"name": "NVIDIA FY2026 Form 10-K (SEC EDGAR)", "url": "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000021/nvda-20260125.htm", "date": "FY ended 25 Jan 2026"},
    "form144": {"name": "Investor.gov — Form 144 (notice of proposed sale)", "url": "https://www.investor.gov/introduction-investing/investing-basics/glossary/form-144", "date": "current"},
    "rule144_guide": {"name": "SEC — Rule 144: Selling Restricted and Control Securities", "url": "https://www.sec.gov/reports/rule-144-selling-restricted-control-securities", "date": "current"},
    "voo_prosp": {"name": "Vanguard S&P 500 ETF prospectus (ETF share class of Vanguard 500 Index Fund)", "url": "https://fund-docs.vanguard.com/p968.pdf", "date": "28 Apr 2026"},
    "voo_ncsrs": {"name": "Vanguard 500 Index Fund semi-annual report (four share classes)", "url": "https://www.sec.gov/Archives/edgar/data/0000036405/000110465926102240/tm2620528d8_ncsrs.htm", "date": "2026"},
    "financebench": {"name": "FinanceBench: A New Benchmark for Financial Question Answering (Patronus AI, arXiv 2311.11944)", "url": "https://arxiv.org/abs/2311.11944", "date": "20 Nov 2023"},
    "nport": {"name": "SEC — Form N-PORT public availability (quarter-end reports)", "url": "https://www.sec.gov/newsroom/press-releases/2025-64", "date": "2025"},
}

# Real BFYP screens used (see assets catalog for exact crops + capture times)
BFYP = {
    "whale_card": "Whale Activity — LIT large transfer card (captured 23 Sep 2026 21:38 UTC)",
    "sm_rows_678": "Smart Money leaderboard rows 6–8 (21:38 UTC)",
    "sm_rows_12": "Smart Money — Scored wallet universe header + rows 1–2 (21:38 UTC)",
    "sm_page": "Smart Money page top: asset consensus note + wallet list (21:38 UTC)",
    "sm_scores": "Smart Money leaderboard score + confidence column (21:38 UTC)",
    "today_lines": "Today — observed lines (21:28 UTC)",
    "today_cats": "Today — category counts card (22:14 UTC)",
    "today_footer": "Today — 'Nothing here is a prediction' footer (22:14 UTC)",
    "spy_cards": "ETF · SPY — net assets / holdings / filed (21:38 UTC)",
    "spy_page": "ETF · SPY — page top with top holdings (22:01 UTC)",
    "spy_bottom": "ETF · SPY — holdings 8–15 + as-filed note (22:01 UTC)",
    "spy_note": "ETF · SPY — as-filed note (22:01 UTC)",
    "voo_cards": "ETF · VOO — fund net assets, whole fund / all share classes (22:01 UTC)",
    "nvda_filings4": "Stocks · NVDA — recent filings (21:39 UTC)",
    "nvda_filings5": "Stocks · NVDA — recent filings incl. N-PX (22:01 UTC)",
    "nvda_fund": "Stocks · NVDA — annual fundamentals as filed (22:01 UTC)",
    "nvda_insider": "Stocks · NVDA — insider forms 3/4/5 (22:01 UTC)",
    "ai_prompt": "AI Research — prompt box (21:39 UTC)",
    "ai_ask": "ETF · SPY — 'Ask BFYP about this' (22:09 UTC)",
    "ai_label": "AI Research — AI label (22:09 UTC)",
    "free_card": "Pricing — Free $0 card (22:09 UTC)",
    "free_list": "Pricing — free plan list (22:09 UTC)",
    "honesty": "Pricing — 'Don't take our word for it' (22:09 UTC)",
}

TAGS_CORE = ["#investing", "#stockmarket", "#fintech"]

REELS = [
  # ------------------------------------------------------------------ LOT 1 — PROOF OVER POSTS
  dict(id="V2-01", slug="sec_hack", lot=1, title="Even the SEC got faked",
       angle="A post is not a source — even an official account was hijacked. Go to the filing.",
       format="News timeline → real filing list", music="cinematic 90 BPM, D minor → drop",
       hook="The SEC’s own account posted fake news.",
       script=[
         "HOOK — 'The SEC's own account posted fake news.' + quoted post (9 Jan 2024, 4:11 pm ET): 'Today the SEC grants approval for #Bitcoin ETFs…' — stamped FAKE",
         "PROOF — 'Bitcoin rose $1,000+. Then fell $2,000+.' (per U.S. DOJ)",
         "PROOF — 4:26 pm ET, Gensler: 'The @SECGov twitter account was compromised… The SEC has not approved…'",
         "TWIST — 'The real approval came the next day — in an official SEC order.'",
         "WHY IT HURTS — 'If an official account can be faked, any post can.'",
         "BFYP — NVDA recent filings, each dated and linked to SEC.gov (spotlight)",
         "CTA — 'Read the filing, not the post.' → betterforyourpocket.com",
       ],
       bfyp=["nvda_filings5"], sources=["sec_x", "gensler_x", "doj_sec_hack", "sec_approval"],
       cover="The SEC’s own account posted fake news.",
       cta="Read the filing, not the post.",
       ig="The SEC's own account once posted fake news. 🔓\n\n9 Jan 2024, 4:11 pm ET: a hijacked @SECGov post said spot bitcoin ETFs were approved. Bitcoin rose $1,000+, then fell $2,000+ after the correction (per the U.S. DOJ). The real approval came the next day, in an official SEC order.\n\nIf an official account can be faked, any post can. The filing is the source.\n\nBFYP puts every filing on one page, dated and linked to SEC.gov.\n→ betterforyourpocket.com (free plan)",
       x="The SEC's own account once posted fake news (9 Jan 2024). BTC +$1,000, then −$2,000 (per DOJ). The real approval came the next day, in an SEC order.\n\nRead the filing, not the post → betterforyourpocket.com",
       tags=["#bitcoin", "#SEC", "#crypto", "#ETF", "#investing", "#duediligence"]),

  dict(id="V2-02", slug="gurus_100m", lot=1, title="Follow filings, not followers",
       angle="Influencer posts can say 'I'm buying'; they can't prove it. Filings can.",
       format="Press-release hook → insider forms", music="UK garage 132 BPM, F minor",
       hook="8 “trading gurus.” $100M. SEC charges.",
       script=[
         "HOOK — '8 “trading gurus.” $100M.' + SEC press release 2022-221 headline card (14 Dec 2022)",
         "PROOF — per the SEC: '…posting price targets or indicating they were buying, holding, or adding to their stock positions.'",
         "PROOF — '…then sold without disclosing it.' (allegations · case pending)",
         "WHY IT HURTS — 'A post can say “I'm buying.” It can't prove it.'",
         "BFYP — NVDA insider forms: officers, directors and 10%+ owners, each Form 4 dated and linked (spotlight)",
         "FACT — 'Form 4 is due before the end of the 2nd business day after the trade.' (SEC Form 4 instructions)",
         "CTA — 'Follow filings, not followers.'",
       ],
       bfyp=["nvda_insider"], sources=["sec_2022_221", "ca5_2025", "form4"],
       cover="8 “trading gurus.” $100M. SEC charges.",
       cta="Follow filings, not followers.",
       ig="8 “trading gurus.” $100M. SEC charges. 📉\n\nIn Dec 2022 the SEC charged eight social media influencers, alleging they hyped stocks to their followers by “posting price targets or indicating they were buying, holding, or adding” — then sold without disclosing it. (Allegations; the related criminal case is still pending.)\n\nA post can say “I'm buying.” It can't prove it.\n\nInsider trades are reported on Form 4, due within two business days. BFYP lists them dated and linked to SEC.gov.\n→ betterforyourpocket.com",
       x="SEC (2022): 8 influencers charged over an alleged $100M pump-and-dump run on Twitter/Discord.\n\nA post can say “buying.” A Form 4 shows it. Follow filings, not followers → betterforyourpocket.com",
       tags=["#stocks", "#SEC", "#investing", "#finfluencer", "#insidertrading", "#duediligence"]),

  dict(id="V2-03", slug="ai_fake_cases", lot=1, title="Fluent isn't true",
       angle="Confident AI can invent sources. In markets a made-up number costs money. BFYP says when data is missing.",
       format="Court-record hook → AI Research honesty", music="minimal tech 120 BPM, G dorian",
       hook="An AI invented 6 court cases. A lawyer filed them.",
       script=[
         "HOOK — 'An AI invented 6 court cases. A lawyer filed them.' (Mata v. Avianca, S.D.N.Y., 2023)",
         "PROOF — court's words: 'non-existent judicial opinions with fake quotes and citations created by the artificial intelligence tool ChatGPT'",
         "PROOF — '$5,000 in sanctions.' (22 Jun 2023)",
         "WHY IT HURTS — 'Confident. Fluent. Wrong.' → 'In markets, a made-up number costs money.'",
         "BFYP — AI Research: every figure traced to the evidence it came from; 'when we do not have the data, the answer says so.' (spotlight)",
         "BFYP — the page labels AI analyses as automated and able to contain errors",
         "CTA — 'Ask with receipts.'",
       ],
       bfyp=["ai_prompt", "ai_label"], sources=["mata"],
       cover="An AI invented 6 court cases. A lawyer filed them.",
       cta="Ask with receipts.",
       ig="An AI invented six court cases. A lawyer filed them. ⚖️\n\nIn Mata v. Avianca (S.D.N.Y., 2023), a federal judge sanctioned lawyers $5,000 for submitting “non-existent judicial opinions with fake quotes and citations” generated by an AI chatbot.\n\nConfident. Fluent. Wrong.\n\nIn markets, a made-up number costs money. BFYP AI Research traces every figure to the evidence it came from, and when we don't have the data, the answer says so.\n→ betterforyourpocket.com",
       x="A federal judge sanctioned lawyers $5,000 for filing AI-invented court cases (Mata v. Avianca, 2023).\n\nFluent isn't true. BFYP AI Research traces every figure to its evidence, and says when data is missing → betterforyourpocket.com",
       tags=["#AI", "#investing", "#fintech", "#research", "#stocks", "#duediligence"]),

  dict(id="V2-04", slug="fake_tweet", lot=1, title="One fake tweet, $136.5B",
       angle="Headlines move markets before anyone verifies. React to what was observed, not to what was posted.",
       format="Big-number hook → Today evidence", music="drum & bass 172 BPM, A minor",
       hook="One fake tweet erased $136.5B.",
       script=[
         "HOOK — 'One fake tweet erased $136.5B in a 3-minute plunge.' (S&P 500 value, per Reuters data · 23 Apr 2013)",
         "PROOF — 'The tweet, from a hacked news account:' quote card of the fake post: 'Breaking: Two Explosions in the White House and Barack Obama is injured' → stamped FAKE",
         "PROOF — 'Dow ↓ ~140 points, within minutes.' → 'Then it bounced back.' (CNBC · Reuters data)",
         "WHY IT HURTS — 'Markets react first. Verification comes later.'",
         "BFYP — Today page: 'What was actually observed.' → '330 observations across 10 assets in the last 24h' (spotlight) → BFYP’s own footer, verbatim: “Observed activity, as counted by BFYP. Nothing here is a prediction.”",
         "CTA — 'Check what actually happened.'",
       ],
       bfyp=["today_lines"], sources=["ap_cnbc", "ap_reuters_abc"],
       cover="One fake tweet erased $136.5B.",
       cta="Check what actually happened.",
       ig="One fake tweet erased $136.5 billion. ⚡️\n\n23 Apr 2013: hackers posted a fake “explosions at the White House” headline from the AP's account. The Dow dropped ~140 points and, per Reuters data, $136.5B of S&P 500 value vanished in a 3-minute plunge, before it was debunked.\n\nMarkets react first. Verification comes later.\n\nBFYP's Today page starts from what was actually observed, counted from evidence. In its own words: “Nothing here is a prediction.”\n→ betterforyourpocket.com",
       x="2013: one fake AP tweet briefly wiped $136.5B off the S&P 500 (Reuters data).\n\nMarkets react first, verify later. Check what was actually observed → betterforyourpocket.com",
       tags=["#stockmarket", "#investing", "#news", "#fakenews", "#trading", "#duediligence"]),

  dict(id="V2-05", slug="fake_reviews", lot=1, title="No testimonials. On purpose.",
       angle="Fake social proof got so common the FTC banned it. BFYP shows zero testimonials and asks to be audited.",
       format="Regulator hook → honesty page", music="amapiano-lite 113 BPM, Bb minor",
       hook="The FTC had to ban fake reviews.",
       script=[
         "HOOK — 'The FTC had to ban fake reviews.' + FTC press release headline (14 Aug 2024)",
         "PROOF — Chair Khan: 'Fake reviews not only waste people's time and money, but also pollute the marketplace…'",
         "TURN — 'So here's our pricing page.'",
         "BFYP — 'We have no testimonials to show you yet, and we are not going to make any up. Audit us instead…' (spotlight)",
         "BFYP — Free plan, $0/month",
         "CTA — 'Don't trust us. Audit us.'",
       ],
       bfyp=["honesty", "free_card"], sources=["ftc_reviews"],
       cover="The FTC had to ban fake reviews.",
       cta="Don't trust us. Audit us.",
       ig="The FTC had to ban fake reviews. ⭐️⭐️⭐️⭐️⭐️\n\nIn Aug 2024 the FTC finalized a rule banning fake reviews and testimonials. Chair Khan: fake reviews “pollute the marketplace.”\n\nSo here's what our pricing page says instead: “We have no testimonials to show you yet, and we are not going to make any up. Audit us instead.”\n\nThe pages are public. They have to agree with each other. Check them.\n→ betterforyourpocket.com ($0 plan)",
       x="The FTC had to ban fake reviews (Aug 2024).\n\nOur pricing page: “We have no testimonials to show you yet, and we are not going to make any up. Audit us instead.” → betterforyourpocket.com",
       tags=["#fintech", "#investing", "#trust", "#startup", "#stocks", "#crypto"]),

  dict(id="V2-06", slug="feed_48", lot=1, title="48% learn investing on social",
       angle="Half of Gen Z investors learn from feeds built for engagement. Ask what a claim is built on.",
       format="Stat hook → evidence lines", music="future bass 150 BPM, D major",
       hook="48% of Gen Z investors learn investing on social media.",
       script=[
         "HOOK — '48%' counter → 'of Gen Z investors learn investing on social media.' (FINRA Foundation & CFA Institute, 2023)",
         "CONTEXT — 'Internet searches: 47%. Parents/family: 45%.'",
         "WHY IT HURTS — 'Feeds reward what's engaging. Not what's verified.'",
         "TURN — 'So ask one thing: what is this built on?'",
         "BFYP — triptych of real screens, each labelled BUILT ON: Today ('from 330 observations') · Whale Activity ('View on explorer' · 'via etherscan') · NVDA fundamentals ('10-K · SEC EDGAR')",
         "CTA — 'Learn from evidence.'",
       ],
       bfyp=["today_lines", "whale_card", "nvda_fund"], sources=["finra_genz"],
       cover="48% learn investing on social media.",
       cta="Learn from evidence.",
       ig="48% of Gen Z investors learn about investing on social media. 📱\n\nThat's from FINRA Foundation & CFA Institute research (2023). Internet searches: 47%. Parents/family: 45%.\n\nFeeds reward what's engaging, not what's verified. So before you act on a post, ask one question: what is this built on?\n\nOn BFYP you can see what a number is built on: observations on the Today page, the raw transaction behind a whale move, the 10-K behind a company figure.\n→ betterforyourpocket.com",
       x="48% of Gen Z investors learn investing on social media (FINRA Foundation/CFA Institute, 2023).\n\nFeeds reward engagement, not verification. Ask what a claim is built on → betterforyourpocket.com",
       tags=["#genz", "#investing", "#financialliteracy", "#personalfinance", "#stocks", "#crypto"]),

  dict(id="V2-07", slug="just_bought", lot=1, title="“Just bought” — just?",
       angle="Holdings disclosures are lagged. 'Just bought' can mean months ago. Check the period and the filing date.",
       format="Timeline explainer → two dates on a fund page", music="synthwave 108 BPM, E minor",
       hook="“Big fund just bought $XYZ!” “Just”?",
       script=[
         "HOOK — typical post (illustration): 'This fund just bought it!' → 'Just?'",
         "TIMELINE — 'Quarter ends 30 Jun' → '13F due within 45 days' → 'You see it mid-August'",
         "WHY IT HURTS — 'The trade itself could be from April.'",
         "RULE — Form 13F: filed within 45 days after quarter end; holdings as of quarter end (Investor.gov)",
         "BFYP — SPY fund page prints two dates: period 2026-06-30 · filed 2026-08-28 (spotlight)",
         "CTA — 'Check both dates.'",
       ],
       bfyp=["spy_cards"], sources=["form13f"],
       cover="“Just bought it”? Check the date.",
       cta="Check both dates.",
       ig="“This fund just bought it!” Just? ⏳\n\nBig-fund holdings reports (Form 13F) show positions as of quarter end, and they can be filed up to 45 days later. A June quarter can surface in mid-August, and the trade itself could be from April.\n\n“Just bought” can mean months ago.\n\nEvery BFYP fund page prints both dates: the period the holdings describe and the day the filing went public.\n→ betterforyourpocket.com",
       x="“Fund just bought X” — often a 13F: holdings as of quarter end, filed up to 45 days later.\n\nAlways check two dates: the period and the filing date → betterforyourpocket.com",
       tags=["#investing", "#stocks", "#ETF", "#13F", "#hedgefunds", "#SEC"]),

  dict(id="V2-08", slug="trace_it", lot=1, title="Can’t trace it? Can’t trust it.",
       angle="Screenshots can be cropped, old or edited. Links can be checked.",
       format="Screenshot glitch → links to raw sources", music="trap 140 BPM, C minor",
       hook="This is a screenshot.",
       script=[
         "HOOK — shutter + generic screenshot (illustration): 'This is a screenshot.'",
         "PROBLEM — 'Cropped? Old? Edited?'",
         "WHY IT HURTS — 'A screenshot can't be checked. A link can.'",
         "BFYP — whale card: 'View on explorer ↗' + 'via etherscan' (spotlight)",
         "BFYP — NVDA filings: 'View on SEC.gov' on every row (spotlight)",
         "CTA — 'Don't trust. Click through.'",
       ],
       bfyp=["whale_card", "nvda_filings4"], sources=[],
       cover="Can’t trace it? Can’t trust it.",
       cta="Don't trust. Click through.",
       ig="This is a screenshot. 📸\n\nIt could be cropped. It could be old. It could be edited. You can't check a screenshot.\n\nYou can check a link.\n\nOn BFYP, every large on-chain move links to the raw transaction on the explorer, and every filing links to the original on SEC.gov.\n\nDon't trust. Click through.\n→ betterforyourpocket.com",
       x="A screenshot can't be checked. A link can.\n\nOn BFYP every whale move links to the raw transaction and every filing links to SEC.gov → betterforyourpocket.com",
       tags=["#crypto", "#onchain", "#ethereum", "#investing", "#DYOR", "#duediligence"]),

  dict(id="V2-09", slug="fiscal_2026", lot=1, title="NVIDIA’s 2026 ended in January",
       angle="Fiscal years don't follow the calendar; comparing the wrong periods tells the wrong story.",
       format="Quiz → period on every figure", music="tech house 126 BPM, B minor",
       hook="When did NVIDIA’s fiscal 2026 end?",
       script=[
         "HOOK — quiz: 'When did NVIDIA's fiscal 2026 end?' A) Dec 31, 2026  B) Dec 31, 2025  C) Jan 25, 2026",
         "REVEAL — 'C. January 25, 2026.' (NVIDIA: fiscal 2026 revenue $215.9B)",
         "INSIGHT — 'Fiscal years don't follow the calendar.'",
         "WHY IT HURTS — 'Compare the wrong periods, get the wrong story.'",
         "BFYP — NVDA fundamentals: '$215.9B · FY2026 · period ended 2026-01-25 · 10-K · SEC EDGAR' (spotlight)",
         "CTA — 'Every number with its period.'",
       ],
       bfyp=["nvda_fund"], sources=["nvda_fy26", "nvda_10k"],
       cover="NVIDIA’s 2026 ended in January.",
       cta="Every number with its period.",
       ig="Quick quiz: when did NVIDIA's fiscal 2026 end? 🧠\n\nA) Dec 31, 2026\nB) Dec 31, 2025\nC) Jan 25, 2026\n\nAnswer: C. NVIDIA's fiscal year 2026 ended January 25, 2026, with $215.9B in revenue.\n\nFiscal years don't follow the calendar. Compare the wrong periods and you get the wrong story.\n\nBFYP prints the period and the source filing under every figure.\n→ betterforyourpocket.com",
       x="Quiz: NVIDIA's fiscal 2026 ended on… Jan 25, 2026.\n\nFiscal ≠ calendar. BFYP prints the period + the filing under every number → betterforyourpocket.com",
       tags=["#nvidia", "#NVDA", "#stocks", "#earnings", "#investing", "#AI"]),

  dict(id="V2-10", slug="top10_36", lot=1, title="500 companies. 36% in 10 lines.",
       angle="'Diversified' index funds can be concentrated. Know what your fund actually holds, as filed.",
       format="Math reveal → real holdings table", music="minimal 118 BPM, E minor",
       hook="You bought 500 companies.",
       script=[
         "HOOK — 'You bought 500 companies.' (SPY holds 504)",
         "REVEAL — '36% of the fund sits in 10 lines.' (counter 0 → 36.4%)",
         "PROOF — top-10 bars as filed: NVDA $58.72B … TSLA $14.35B = $284.48B of $781.19B",
         "TWIST — 'And Alphabet shows up twice.' → '10 lines. 9 companies.'",
         "BFYP — SPY page: top holdings, % of net assets as filed (spotlight)",
         "CTA — 'See what your fund actually holds.'",
       ],
       bfyp=["spy_page", "spy_cards"], sources=[],
       cover="500 companies. 36% in 10 lines.",
       cta="See what your fund actually holds.",
       ig="You bought 500 companies. 36% of your money sits in 10 lines. 📊\n\nSPY's latest public holdings (N-PORT, period 30 Jun 2026, filed 28 Aug 2026): the top 10 holdings add up to $284.48B of $781.19B in net assets, or 36.4%.\n\nAnd Alphabet appears twice (GOOGL + GOOG). So that's 10 lines and 9 companies.\n\nBFYP shows what a fund actually holds, as filed, with the period and the filing date.\n→ betterforyourpocket.com",
       x="SPY holds 504 names, but its top 10 = 36.4% of net assets (N-PORT, period 30 Jun 2026). Alphabet appears twice.\n\nSee what your fund actually holds → betterforyourpocket.com",
       tags=["#ETF", "#SP500", "#SPY", "#investing", "#indexfunds", "#stocks"]),

  # ------------------------------------------------------------------ LOT 2 — YOUR RESEARCH STACK IS BROKEN
  dict(id="V2-11", slug="eleven_tabs", lot=2, title="POV: 11 tabs for one ticker",
       angle="Fragmented research wastes time and still misses what changed. One workflow, sources attached.",
       format="POV tab chaos → one-flow montage", music="tech house 128 BPM, G minor",
       hook="POV: 11 tabs to check one ticker.",
       script=[
         "HOOK — tabs cascade (generic): price chart, X search, forum thread, EDGAR, block explorer, news, AI chatbot, Discord, spreadsheet, earnings PDF, another chart",
         "PROBLEM — '…and you still don't know what changed.'",
         "TURN — tabs collapse: 'One workflow.'",
         "BFYP montage — Today (what changed) → Whale Activity (who moved) → Smart Money (who's good) → Stock page (what was filed) → AI Research (ask, with receipts)",
         "PAYOFF — 'Sources attached. Every step.'",
         "CTA — 'Close 10 tabs.'",
       ],
       bfyp=["today_cats", "whale_card", "sm_rows_678", "nvda_filings4", "ai_prompt"], sources=[],
       cover="POV: 11 tabs to check one ticker.",
       cta="Close 10 tabs.",
       ig="POV: 11 tabs open to check one ticker. 🗂️\n\nPrice chart. X search. Forum thread. EDGAR. Block explorer. News. Chatbot. Discord. Spreadsheet. Earnings PDF. Another chart.\n\n…and you still don't know what changed.\n\nBFYP puts it in one workflow: what changed today, who moved, which wallets have a track record, what was filed, and AI answers that keep receipts.\n\nClose 10 tabs → betterforyourpocket.com",
       x="POV: 11 tabs to research one ticker, and you still don't know what changed.\n\nOne workflow, sources attached → betterforyourpocket.com",
       tags=["#investing", "#stocks", "#crypto", "#productivity", "#fintech", "#research"]),

  dict(id="V2-12", slug="what_changed", lot=2, title="Prices move. What changed?",
       angle="Price tells you that something moved, not what. Start from observed activity.",
       format="Color-flash hook → Today counts", music="minimal 122 BPM, F# minor",
       hook="Your dashboard, all day: GREEN. RED. It shows prices. Not what changed.",
       script=[
         "HOOK — 'Your dashboard, all day:' + flashing 'GREEN. RED. GREEN. RED.' → 'It shows prices. Not what changed.'",
         "WHY IT HURTS — 'Price tells you THAT. Not WHAT.'",
         "BFYP — Today: counter to '354 observations' in the last 24h · 10 assets",
         'BFYP — spotlight tour of the category card: on-chain 234 · companies & themes 101 · crypto 11 · macro & regulation 5 · stocks & ETFs 3',
         "BFYP — 'These are counts of observations — not price movement, and not a measure of size.' (spotlight)",
         "CTA — 'Start with what changed.' · 'Observed activity. Nothing here is a prediction.'",
       ],
       bfyp=["today_cats"], sources=[],
       cover="Prices move. What changed?",
       cta="Start with what changed.",
       ig="Your dashboard shows prices. It doesn't show what changed. 🟢🔴\n\nPrice tells you THAT something moved. Not WHAT.\n\nBFYP's Today page starts from observed activity: 354 observations in 24 hours across 10 assets, counted by category (on-chain, companies & themes, crypto, macro & regulation, stocks & ETFs).\n\nCounts, not predictions.\n→ betterforyourpocket.com",
       x="Price tells you THAT something moved. Not WHAT.\n\nBFYP Today: what was actually observed in the last 24h, by category, with evidence → betterforyourpocket.com",
       tags=["#investing", "#stockmarket", "#crypto", "#markets", "#trading", "#fintech"]),

  dict(id="V2-13", slug="since_when", lot=2, title="“Whales are buying.” Since when?",
       angle="A number without a time window is noise. Every BFYP figure carries its window.",
       format="Interrogation → windows montage", music="UK garage 130 BPM, C minor",
       hook="“Whales are buying!” Since when?",
       script=[
         "HOOK — typical post (illustration): '🐋 Whales are buying! 🚀' + VO → 'Since when?'",
         "WHY IT HURTS — 'A number without a timeframe is just noise.'",
         "BFYP — 'On BFYP, every number carries its window.' (Today card)",
         "BFYP — window montage on real screens: 24 HOURS (Today: 'in the last 24h') · 7 DAYS (Smart Money: '7-day census') · 30 DAYS (Smart Money: '(30D)') · 2 HOURS AGO (Whale Activity: 'observed 2 hours ago')",
         "PAYOFF — 'If it has no window, it's a vibe.'",
         "CTA — 'Numbers with a timeframe.'",
       ],
       bfyp=["today_lines", "sm_page", "whale_card"], sources=[],
       cover="“Whales are buying.” Since when?",
       cta="Numbers with a timeframe.",
       ig="“Whales are buying.” Since when? 🐋⏱️\n\nA number without a timeframe is just noise. Buying since an hour ago? A month? Which wallets?\n\nOn BFYP every figure carries its window: “in the last 24h”, “7-day census”, “30D”, “observed 2 hours ago”.\n\nIf it has no window, it's a vibe.\n→ betterforyourpocket.com",
       x="“Whales are buying.” Since when?\n\nOn BFYP every number carries its window: 24h, 7-day, 30D, observed time → betterforyourpocket.com",
       tags=["#crypto", "#whales", "#onchain", "#bitcoin", "#investing", "#smartmoney"]),

  dict(id="V2-14", slug="whale_alert", lot=2, title="This whale alert tells you nothing",
       angle="Bare alerts give size without context. BFYP types, groups, scores and sources every large move.",
       format="Alert illustration → spotlight tour of the real whale card", music="tech house 124 BPM, A minor",
       hook="This whale alert tells you nothing.",
       script=[
         "HOOK — 'This whale alert tells you nothing.' + typical alert (illustration): '🚨🐋 $1.09M $LIT just moved!'",
         "QUESTIONS — 'Who is the wallet?' 'One transfer or many?' 'Where is the proof?'",
         "WHY IT HURTS — 'Size without context is just noise.'",
         "BFYP — same move on BFYP, spotlight tour: typed + sized (Large transfer · $1.09M LIT) → grouped (2 similar transfers) → wallet + chain → wallet score + ROI → raw transaction link → observed/detected via etherscan",
         "PAYOFF — 'Not an alert. Evidence.'",
         "CTA — 'Read the evidence, not the alert.' (whale feed on the free plan)",
       ],
       bfyp=["whale_card"], sources=[],
       cover="This whale alert tells you nothing.",
       cta="Read the evidence, not the alert.",
       ig="This whale alert tells you nothing. 🐋\n\n“$1.09M $LIT just moved!” OK… Who is the wallet? One transfer or many? Where's the proof?\n\nSame move on BFYP: typed as a large transfer, grouped (2 similar transfers of ~$544K), wallet + chain, the wallet's score and ROI, a link to the raw transaction, and when it was observed and detected (via etherscan).\n\nNot an alert. Evidence. The whale feed is on the free plan.\n→ betterforyourpocket.com",
       x="“$1.09M just moved!” tells you nothing.\n\nOn BFYP the same move is typed, grouped, scored and linked to the raw tx → betterforyourpocket.com",
       tags=["#crypto", "#whalealert", "#onchain", "#ethereum", "#altcoins", "#DYOR"]),

  dict(id="V2-15", slug="context_paste", lot=2, title="Stop pasting tickers into chatbots",
       angle="Generic chatbots lack context; you re-explain every time. On BFYP the asset comes with you.",
       format="Chat illustration → Ask BFYP about this", music="amapiano-lite 115 BPM, Eb minor",
       hook="Copy. Paste. Explain. Repeat.",
       script=[
         "HOOK — generic chat box (illustration) typing 'Here's SPY's latest filing, top holdings and what changed today…' → 'Copy. Paste. Explain. Repeat.'",
         "WHY IT HURTS — 'Your chatbot doesn't know what you're looking at.'",
         "BFYP — SPY page: 'Ask BFYP about this — Open AI Research with SPY already in context.' (spotlight)",
         "BFYP — suggested questions: 'What changed in SPY over the last 24 hours?' 'Which filings has SPY made recently?'",
         "BFYP — 'Nothing is sent and no credits are used until you ask.' (spotlight)",
         "CTA — 'The asset comes with you.'",
       ],
       bfyp=["ai_ask"], sources=[],
       cover="Stop pasting tickers into chatbots.",
       cta="The asset comes with you.",
       ig="Copy. Paste. Explain. Repeat. 🤖\n\nEvery time you ask a generic chatbot about a ticker, you have to rebuild the context: the filing, the holdings, what changed today…\n\nOn BFYP, open AI Research from any fund or company page and the asset is already in context. Suggested questions included.\n\nNothing is sent and no credits are used until you ask.\n→ betterforyourpocket.com",
       x="Stop pasting tickers into chatbots.\n\nOn BFYP, AI Research opens with the asset already in context, and nothing is sent until you ask → betterforyourpocket.com",
       tags=["#AI", "#investing", "#ETF", "#fintech", "#productivity", "#stocks"]),

  dict(id="V2-16", slug="cost_before", lot=2, title="Know the cost before you ask",
       angle="AI research costs should be visible before you ask, not after.",
       format="Price-tag hook → credits shown up front", music="synthwave 110 BPM, F minor",
       hook="What did that AI answer actually cost you?",
       script=[
         "HOOK — 'What did that AI answer actually cost you?'",
         "WHY IT HURTS — 'You shouldn't find out after.'",
         "BFYP — AI Research shows '36 credits per question' before you ask (spotlight)",
         "BFYP — free plan: '52 AI credits/month (= 7 reports)' · 'AI Research: 2–172 credits/question by depth'",
         "BFYP — 'Nothing is sent and no credits are used until you ask.'",
         "CTA — '52 free AI credits every month.'",
       ],
       bfyp=["ai_prompt", "free_list", "free_card"], sources=[],
       cover="Know the cost before you ask.",
       cta="52 free AI credits every month.",
       ig="What did that AI answer actually cost you? 💳\n\nYou shouldn't find out after.\n\nOn BFYP the cost is on screen before you ask (e.g. “36 credits per question”), questions range from 2 to 172 credits by depth, and nothing is sent until you hit ask.\n\nThe free plan includes 52 AI credits a month (= 7 reports).\n→ betterforyourpocket.com",
       x="Know the cost before you ask.\n\nBFYP shows the credit cost up front, sends nothing until you ask, and the free plan includes 52 AI credits/month → betterforyourpocket.com",
       tags=["#AI", "#fintech", "#investing", "#research", "#stocks", "#crypto"]),

  dict(id="V2-17", slug="free_speedrun", lot=2, title="Everything $0 gets you",
       angle="The free plan, listed exactly as the pricing page lists it, in 15 seconds.",
       format="Speed-run checklist", music="future bass 150 BPM, E major",
       hook="$0. Here’s everything it gets you.",
       script=[
         "HOOK — giant '$0' → 'Here's everything it gets you.'",
         "LIST — dashboard & live market overview · whale activity feed · Smart Money leaderboard · token, stock & ETF research pages · 3 watchlist entries · 3 alert rules + 10 whale alerts/month · 52 AI credits/month · CSV export preview (100 rows) · community support",
         "BFYP — real pricing screens: Free $0/month + the free-plan list",
         "CTA — 'Create a free account.'",
       ],
       bfyp=["free_card", "free_list"], sources=[],
       cover="$0. Here’s everything it gets you.",
       cta="Create a free account.",
       ig="$0. Here's everything it gets you. ✅\n\n• Dashboard & live market overview\n• Whale activity feed\n• Smart Money leaderboard\n• Token, stock & ETF research pages\n• 3 watchlist entries\n• 3 alert rules · 10 whale alerts/month\n• 52 AI credits/month (= 7 reports)\n• AI Research: 2–172 credits/question by depth\n• CSV export preview (100 rows)\n• Community support\n\nAs listed on the pricing page (captured 23 Sep 2026).\n→ betterforyourpocket.com",
       x="$0/month on BFYP: whale feed, Smart Money leaderboard, token/stock/ETF pages, 52 AI credits/month, alerts, CSV preview.\n\n→ betterforyourpocket.com",
       tags=["#fintech", "#investing", "#crypto", "#stocks", "#free", "#tools"]),

  dict(id="V2-18", slug="whose_trillion", lot=2, title="$1.67 trillion. Whose?",
       angle="The same fund number can cover different scopes. Know what a number covers.",
       format="Myth → fact", music="minimal 120 BPM, D minor",
       hook="VOO: $1.67 trillion?",
       script=[
         "HOOK — 'VOO:' + counter to '$1.67T' + '?' → 'Not exactly.'",
         "FACT — 'VOO is one share class of the Vanguard 500 Index Fund.' (Vanguard prospectus)",
         "FACT — diagram of the fund's four share classes: Investor · ETF (VOO) · Admiral · Institutional Select (2026 semi-annual report; not to scale)",
         "BFYP — VOO card tour: 'FUND NET ASSETS $1671.23B · period 2026-06-30' → 'whole fund, all share classes' → the scope sits next to the number",
         "PAYOFF — 'BFYP labels what every number covers.'",
         "CTA — 'Know what a number covers.'",
       ],
       bfyp=["voo_cards"], sources=["voo_prosp", "voo_ncsrs"],
       cover="$1.67 trillion. Whose?",
       cta="Know what a number covers.",
       ig="VOO: $1.67 trillion? Not exactly. 🔍\n\nVOO is the ETF share class of the Vanguard 500 Index Fund, which has four share classes. The $1,671.23B in the fund's filing (period 30 Jun 2026) is the whole fund, all share classes.\n\nSame number, different scope.\n\nBFYP labels what every figure covers, right next to the number.\n→ betterforyourpocket.com",
       x="VOO = one share class of the Vanguard 500 Index Fund. The $1.67T in its N-PORT covers the whole fund, all share classes.\n\nKnow what a number covers → betterforyourpocket.com",
       tags=["#VOO", "#ETF", "#vanguard", "#SP500", "#investing", "#indexfunds"]),

  dict(id="V2-19", slug="form_144", lot=2, title="A Form 144 isn't a sale",
       angle="Form 144 is a notice of a proposed sale; people read it as insiders dumping. Read what was filed.",
       format="Myth → fact → filings", music="trap 140 BPM, G minor",
       hook="Three Form 144 filings on NVIDIA in September. Insiders dumping?",
       script=[
         "HOOK — real NVDA filings list: three '144' rows filed in September 2026 highlighted → 'Insiders dumping?'",
         "FACT — 'A Form 144 is a notice of a proposed sale.' (Investor.gov)",
         "FACT — SEC staff guidance quote: 'If a person who has filed a Form 144 does not sell the securities referred to therein, no amendment reflecting this fact need be filed.'",
         "PAYOFF — 'Filed ≠ sold.'",
         "BFYP — NVDA insider forms: 'Completed insider trades show up on Form 4.' (real Form 4 rows, dated and linked)",
         "CTA — 'Read what was actually filed.'",
       ],
       bfyp=["nvda_filings5", "nvda_insider"], sources=["form144", "rule144_guide"],
       cover="A Form 144 isn't a sale.",
       cta="Read what was filed.",
       ig="3 Form 144s on NVIDIA in September. Insiders dumping? 🤔\n\nA Form 144 is a notice of a proposed sale. And per SEC staff guidance, if the filer doesn't end up selling, no amendment is required.\n\nFiled ≠ sold. Completed insider trades are reported on Form 4.\n\nBFYP lists every filing dated and linked to the original on SEC.gov, so you can read what was actually filed.\n→ betterforyourpocket.com",
       x="Form 144 = notice of a PROPOSED sale, not proof of one (Investor.gov / SEC).\n\nFiled ≠ sold. Read the original, dated & linked → betterforyourpocket.com",
       tags=["#NVDA", "#stocks", "#insidertrading", "#SEC", "#investing", "#nvidia"]),

  dict(id="V2-20", slug="financebench", lot=2, title="Fast doesn’t matter if it’s wrong",
       angle="A benchmark on SEC filings found a top AI setup wrong or refusing 81% of the time. Finance needs receipts.",
       format="Stat hook → traced answers", music="drum & bass 170 BPM, E minor",
       hook="81% wrong or refused.",
       script=[
         "HOOK — '81%' → 'of questions about SEC filings: answered wrong or refused.' (GPT-4-Turbo + retrieval · FinanceBench, Patronus AI, Nov 2023)",
         "WHY IT HURTS — 'Fast. Fluent. Unchecked.'",
         "TURN — 'Finance needs receipts.'",
         "BFYP — 'Start from the filing': NVDA fundamentals as filed, swept card by card: Revenue $215.9B · Net income $120.1B · Total assets $206.8B · Total liabilities $49.5B — each 'FY2026 · period ended 2026-01-25 · 10-K · SEC EDGAR'",
         "PAYOFF — 'Four figures. Four receipts.'",
         "CTA — 'Answers you can audit.'",
       ],
       bfyp=["nvda_fund"], sources=["financebench", "nvda_fy26", "nvda_10k"],
       cover="81% wrong or refused.",
       cta="Answers you can audit.",
       ig="81% wrong or refused. 🤖📉\n\nIn the FinanceBench study (Patronus AI, Nov 2023), GPT-4-Turbo with a retrieval system incorrectly answered or refused 81% of sample questions about public-company filings. (One test setup, 2023 models.)\n\nFast doesn't matter if it's wrong.\n\nOn BFYP, company figures come as filed: every number with its period and the 10-K it came from. Four figures, four receipts. Then ask AI Research, with the evidence attached.\n→ betterforyourpocket.com",
       x="FinanceBench (2023): GPT-4-Turbo + retrieval got 81% of SEC-filing questions wrong or refused.\n\nStart from the filing: every figure with its period and its 10-K → betterforyourpocket.com",
       tags=["#AI", "#LLM", "#fintech", "#investing", "#SEC", "#research"]),

  # ------------------------------------------------------------------ LOT 3 — BAD MARKET HABITS
  dict(id="V2-21", slug="big_not_smart", lot=3, title="Biggest wallet ≠ smartest wallet",
       angle="Size is visible; skill isn't. Wallets should be categorized by behavior, never size alone.",
       format="Myth vs fact", music="drum & bass 174 BPM, F minor",
       hook="The biggest wallet isn't the smartest one.",
       script=[
         "HOOK — 'The biggest wallet isn't the smartest one.' + bubbles: BIGGEST ($$$$$) ≠ SMARTEST? (illustration) with labels 'SIZE · OBVIOUS' and 'SKILL · ?'",
         "WHY IT HURTS — 'Size is easy to see. Skill isn't.'",
         "BFYP — Scored wallet universe: 'Behavioral categories from observed metrics — never from size alone.' (spotlight)",
         'BFYP — each wallet: category + score /100 + confidence badge (spotlight on a real row)',
         "CTA — 'Ranked on what they did.'",
       ],
       bfyp=["sm_rows_12"], sources=[],
       cover="Biggest wallet ≠ smartest wallet.",
       cta="Ranked on what they did.",
       ig="The biggest wallet isn't the smartest one. 🐳≠🧠\n\nSize is easy to see. Skill isn't.\n\nBFYP's Smart Money leaderboard puts wallets into behavioral categories from observed metrics, never from size alone, and every score sits next to its confidence level.\n\nRanked on what they did, not how big they are.\n→ betterforyourpocket.com",
       x="Biggest wallet ≠ smartest wallet.\n\nBFYP categorizes wallets from observed behavior, never size alone → betterforyourpocket.com",
       tags=["#crypto", "#smartmoney", "#onchain", "#whales", "#DeFi", "#investing"]),

  dict(id="V2-22", slug="market_maker", lot=3, title="That whale might be a market maker",
       angle="Not every big wallet is a conviction buyer; some make markets. Label wallets by behavior.",
       format="Reveal", music="amapiano-lite 112 BPM, A minor",
       hook="That “whale”? Might be a market maker.",
       script=[
         "HOOK — 'That “whale”? Might be a market maker.'",
         "WHY IT HURTS — 'Market makers move size all day. It's their job.'",
         "BFYP — leaderboard tags: MARKET MAKER vs WHALE ACCUMULATOR (spotlight)",
         "PAYOFF — 'Same size. Different behavior.'",
         "CTA — 'Know who you're watching.'",
       ],
       bfyp=["sm_rows_678"], sources=[],
       cover="That “whale” might be a market maker.",
       cta="Know who you're watching.",
       ig="That “whale”? It might be a market maker. 🔁\n\nMarket makers move size all day; providing liquidity is their job. Reading every big transfer as conviction buying is how people get faked out.\n\nBFYP's Smart Money leaderboard labels wallets by behavior, e.g. “Market maker” vs “Whale accumulator”, next to a score and a confidence badge.\n→ betterforyourpocket.com",
       x="That “whale” might be a market maker.\n\nBFYP labels wallets by behavior (market maker vs whale accumulator) → betterforyourpocket.com",
       tags=["#crypto", "#whales", "#onchain", "#smartmoney", "#trading", "#DYOR"]),

  dict(id="V2-23", slug="same_score", lot=3, title="Same score. Not the same thing.",
       angle="Two identical scores with different confidence are not equal. Read the badge.",
       format="Spot the difference (split screen)", music="synthwave 106 BPM, C minor",
       hook="31/100 vs 31/100. Same score?",
       script=[
         "HOOK — split screen: '31/100' | '31/100' → 'Same score?'",
         "REVEAL — badges: 'ESTIMATED' vs 'HIGH CONFIDENCE' (real leaderboard rows 6 and 7)",
         "PAYOFF — 'Same number. Different confidence.'",
         "LESSON — 'Read the badge, not just the number.'",
         "CTA — 'Scores with their confidence.'",
       ],
       bfyp=["sm_rows_678"], sources=[],
       cover="Same score. Not the same thing.",
       cta="Scores with their confidence.",
       ig="31/100 vs 31/100. Same score? 👀\n\nNot the same thing. On BFYP's Smart Money leaderboard one is marked ESTIMATED, the other HIGH CONFIDENCE.\n\nSame number, different confidence. Read the badge, not just the number.\n→ betterforyourpocket.com",
       x="Two wallets, both 31/100. One ESTIMATED, one HIGH CONFIDENCE.\n\nRead the badge, not just the number → betterforyourpocket.com",
       tags=["#crypto", "#smartmoney", "#onchain", "#data", "#investing", "#trading"]),

  dict(id="V2-24", slug="three_wins", lot=3, title="3 wins. Genius or luck?",
       angle="Short track records can't separate skill from luck. Thin history should read 'Unproven'.",
       format="Coin-flip quiz", music="UK garage 134 BPM, A minor",
       hook="Three wins in a row. Genius, or luck?",
       script=[
         "HOOK — 'W W W' cards + 'Three wins in a row.' → 'Genius, or luck?' (coin flip)",
         "WHY IT HURTS — 'Honestly? A short track record can't tell you.'",
         "INSIGHT — 'Three good calls is a sample, not a style.'",
         "BFYP — Smart Money: 'Thin history reads “Unproven”, not a style claim.' (spotlight)",
         "CTA — 'Scores that admit what they don't know.'",
       ],
       bfyp=["sm_rows_12"], sources=[],
       cover="3 wins in a row. Genius or luck?",
       cta="Scores that admit what they don't know.",
       ig="3 wins in a row. Genius or luck? 🪙\n\nA short track record can't tell you. Three good calls is a sample, not a style.\n\nOn BFYP's Smart Money leaderboard, thin history reads “Unproven”, not a style claim.\n\nScores that admit what they don't know.\n→ betterforyourpocket.com",
       x="3 wins in a row: genius or luck? A short record can't tell.\n\nOn BFYP, thin history reads “Unproven” → betterforyourpocket.com",
       tags=["#trading", "#crypto", "#smartmoney", "#investing", "#psychology", "#onchain"]),

  dict(id="V2-25", slug="both_ways", lot=3, title="The data pointed both ways",
       angle="Real data is often mixed. A feed that only shows one direction is telling a story.",
       format="Split arrows → Today line", music="minimal 118 BPM, B minor",
       hook="On USDC, the data pointed both ways.",
       script=[
         "HOOK — ↑ ↓ split → 'On USDC, the data pointed both ways.'",
         "WHY IT HURTS — 'A feed that picks a side is telling you a story.'",
         "BFYP — Today: 'On USDC, observations point in both directions. · from one group' (spotlight)",
         "PAYOFF — 'Mixed is information too.'",
         "CTA — 'See both sides.'",
       ],
       bfyp=["today_lines"], sources=[],
       cover="The data pointed both ways.",
       cta="See both sides.",
       ig="On USDC, the data pointed both ways. ↕️\n\nMixed signals are real. A feed that only ever shows one direction is telling you a story.\n\nBFYP's Today page says it plainly when observations point in both directions, and shows the group of evidence behind it.\n\nMixed is information too.\n→ betterforyourpocket.com",
       x="Sometimes the data points both ways, and that's information.\n\nBFYP Today says so plainly, with the evidence → betterforyourpocket.com",
       tags=["#crypto", "#stablecoins", "#onchain", "#markets", "#investing", "#data"]),

  dict(id="V2-26", slug="together", lot=3, title="Alone it's noise",
       angle="Single observations are noise; different kinds occurring together on one wallet are worth a look.",
       format="Dots connect → Today line", music="tech house 125 BPM, D minor",
       hook="One signal alone? Noise.",
       script=[
         "HOOK — a single pulsing dot → 'One signal alone? Noise.'",
         "BUILD — dots connect: 'Two different kinds, same wallet?'",
         "BFYP — Today: '4 observations of 2 different kinds are occurring together on 0xe1ad…1691 · from one group' (spotlight)",
         "PAYOFF — 'Worth a look. Not a signal to trade — a lead to check.'",
         "CTA — 'See what's happening together.'",
       ],
       bfyp=["today_lines"], sources=[],
       cover="Alone it's noise.",
       cta="See what's happening together.",
       ig="One signal alone? Noise. 🔗\n\nFour observations of two different kinds, on the same wallet, at the same time? That's worth a look.\n\nBFYP's Today page groups observations that occur together and links them to the evidence.\n\nNot a trade signal. A lead you can check.\n→ betterforyourpocket.com",
       x="One observation alone is noise. Different kinds occurring together on one wallet? Worth a look.\n\nBFYP Today groups them, with evidence → betterforyourpocket.com",
       tags=["#crypto", "#onchain", "#ethereum", "#DeFi", "#investing", "#research"]),

  dict(id="V2-27", slug="prove_it", lot=3, title="If it can’t be proven wrong, it’s a vibe",
       angle="Unfalsifiable takes are vibes. Every BFYP Today line names what would prove it.",
       format="Manifesto with strike-throughs", music="cinematic 92 BPM, E minor → drop",
       hook="If it can’t be proven wrong, it’s just a vibe.",
       script=[
         "HOOK — 'If it can't be proven wrong, it's just a vibe.'",
         "EXAMPLES (struck through) — '“It'll pump eventually.”' '“Smart money knows.”' '“Trust me.”'",
         "BFYP — Today: 'No model produces them, and every one names what would prove it.' (spotlight)",
         "PAYOFF — 'Claims you can check.'",
         "CTA — 'Trade vibes for evidence.'",
       ],
       bfyp=["today_lines"], sources=[],
       cover="If it can’t be proven wrong, it’s a vibe.",
       cta="Trade vibes for evidence.",
       ig="If it can't be proven wrong, it's just a vibe. ✨\n\n“It'll pump eventually.” “Smart money knows.” “Trust me.” None of these can ever be wrong, so none of them tell you anything.\n\nOn BFYP's Today page no model produces the lines, and every one names what would prove it.\n\nClaims you can check.\n→ betterforyourpocket.com",
       x="If a take can't be proven wrong, it's a vibe.\n\nEvery BFYP Today line names what would prove it → betterforyourpocket.com",
       tags=["#investing", "#crypto", "#stocks", "#criticalthinking", "#markets", "#research"]),

  dict(id="V2-28", slug="no_invented", lot=3, title="We won’t invent a consensus",
       angle="When there's no data, the honest output is nothing. BFYP says so instead of inventing a number.",
       format="Empty-state manifesto", music="cinematic 88 BPM, G minor",
       hook="No data? Then show nothing.",
       script=[
         "HOOK — 'No data? Then show nothing.' + an honest empty consensus box",
         "WHY IT HURTS — 'A guess dressed up as data is worse than a blank.' + an invented '87% consensus' card stamped MADE UP (illustration of what not to do)",
         "BFYP — Smart Money page, verbatim: 'When no scored wallet was active, we say so instead of inventing a consensus.' (spotlight on the real line)",
         "BFYP — Today: 'A group with none in it is not shown.' (spotlight)",
         "PAYOFF — 'Empty is an answer.'",
         "CTA — 'Data that doesn't pretend.'",
       ],
       bfyp=["sm_page", "today_cats"], sources=[],
       cover="We won’t invent a consensus.",
       cta="Data that doesn't pretend.",
       ig="When there's no data, what does your dashboard show? 🫥\n\nBFYP's Smart Money page: “When no scored wallet was active, we say so instead of inventing a consensus.”\n\nToday page: “A group with none in it is not shown.”\n\nEmpty is an answer. Data that doesn't pretend.\n→ betterforyourpocket.com",
       x="“When no scored wallet was active, we say so instead of inventing a consensus.”\n\nEmpty is an answer → betterforyourpocket.com",
       tags=["#data", "#crypto", "#smartmoney", "#investing", "#fintech", "#onchain"]),

  dict(id="V2-29", slug="timestamps", lot=3, title="Why every screen we post is timestamped",
       angle="Screenshots age instantly. We stamp ours so you know when, and check the live page for now.",
       format="Brand manifesto", music="trap 144 BPM, D minor",
       hook="Every screenshot starts aging the second it’s taken.",
       script=[
         "HOOK — 'Every screenshot starts aging the second it's taken.' (a real Today card slowly desaturates, age counter ticking)",
         "PROOF — same BFYP Today page, 46 minutes apart: '330 observations' (21:28 UTC) vs '354 observations' (22:14 UTC)",
         "PROOF — counter 330 → 354: 'Same page. Same day. Different number.'",
         "BFYP — 'That's why every screen we post carries its capture time.' Capture pills fly in: 21:28 · 21:38 · 21:39 · 22:01 · 22:09 · 22:14 UTC",
         "TRUTH — 'By the time you watch this, the live page has moved on.'",
         "CTA — 'Check the live page.'",
       ],
       bfyp=["today_lines", "today_head", "whale_card", "nvda_filings4", "spy_page", "ai_ask", "today_cats"], sources=[],
       cover="Every screenshot starts aging.",
       cta="See today's version live.",
       ig="Every screenshot starts aging the second it's taken. ⏱️\n\nSame BFYP Today page, 46 minutes apart: 330 observations, then 354. That's why every BFYP screen we post carries its capture time, down to the minute (these were captured 23 Sep 2026, UTC).\n\nBy the time you watch this, the live pages have moved on. That's the point: check the live page, not our screenshot.\n→ betterforyourpocket.com",
       x="Every screenshot starts aging the second it's taken. We timestamp ours to the minute.\n\nCheck the live page, not the screenshot → betterforyourpocket.com",
       tags=["#investing", "#data", "#fintech", "#crypto", "#stocks", "#transparency"]),

  dict(id="V2-30", slug="no_source", lot=3, title="No source? It's just content.",
       angle="Rumor < screenshot < headline < official filing, dated and linked. Only the top rung is proof, and BFYP shows it.",
       format="Evidence ladder", music="future bass 148 BPM, A major",
       hook="No source? It's just content.",
       script=[
         "HOOK — 'No source? It's just content.'",
         "LADDER — 'The evidence ladder: from weakest to strongest' → 'Rumor' → 'Screenshot' → 'Headline' → 'Official filing, dated and linked'",
         "BFYP — 'On BFYP, every number has its source.' NVDA: '$215.9B · FY2026 · period ended 2026-01-25 · 10-K · SEC EDGAR' (spotlight: 'Fiscal year ended 2026-01-25 · 10-K · SEC')",
         "BFYP — 'And the link to the original.' SPY: 'As filed with the SEC (original N-PORT filing)' (spotlight: 'N-PORT filed with the SEC')",
         "CTA — 'Go back to the source.' · 'Free at betterforyourpocket.com'",
       ],
       bfyp=["nvda_fund", "spy_note"], sources=[],
       cover="No source? It's just content.",
       cta="Go back to the source.",
       ig="No source? It's just content. 🔎\n\nRumor → screenshot → headline → official filing, dated and linked. Only the last rung is proof.\n\nOn BFYP, every number shows its period and the document it comes from (10-K, N-PORT…), with a link to the original on SEC.gov.\n\nGo back to the source. Free.\n→ betterforyourpocket.com",
       x="No source? It's just content.\n\nOn BFYP, every number comes with its period, its filing and a link to the original → betterforyourpocket.com",
       tags=["#investing", "#stocks", "#ETF", "#SEC", "#duediligence", "#finance"]),
]
